# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Village - Learning never ends !
email: xmaimom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I am a Solutions-oriented software professional offering outstanding technical proficiency and extensive practical skills achieved with 10 years of progressive career in implementing development and enhancement projects !
baseurl: "" # the subpath of your site, e.g. /blog
url: "maimom.github.io" # the base hostname & protocol for your site
twitter_username: MaimomItao
github_username:  Maimom

# Build settings
markdown: kramdown
